server:
  port: 5555
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: zuulsvr

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    licensingservice: /licensingservice/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
    routes:
      enabled: true
    health:
      enabled: true